import './button/scripts'
import './collapseCard/scripts'
import './dropdownMenu/scripts'
import './menuList/scripts'
import './tabs/scripts'
import './select_custom/scripts'
import './select_multiSelect/scripts'
