import './hello/scripts'
import './button/scripts'
import './dropdownMenu/scripts'
import './menuList/scripts'
import './tabs/scripts'
import './input_text/scripts'
import './select_custom/scripts'
import './select_multiSelect/scripts'
